spring:
  application:
    name: msvc-student       # Nombre del microservicio, usado para registrarse en Eureka y para configuraci칩n remota.
  config:
    # Indica que debe importar la configuraci칩n desde un Config Server alojado en http://localhost:8888.
    # "optional:" significa que si el Config Server no est치 disponible, la app sigue funcionando con su configuraci칩n local.
    import: optional:configserver:http://localhost:8888